:: 제품게시글 글올리기 ::
INSERT INTO PRODBOARD VALUES
((SELECT NVL(MAX(BOARD_ID),0)+1 FROM PRODBOARD),'책꽂이/책상 판매합니다.',
'한가람 아파트에서 직접가져가셔야합니다','F',SYSDATE,SYSDATE,'P0028','testing',30000);


INSERT INTO PRODBOARD VALUES
((SELECT NVL(MAX(BOARD_ID),0)+1 FROM PRODBOARD),'로이드 14K 별자리 목걸이',
'쇼핑백은 살짝 구겨졌지만 새상품이예요~ 7월 게자리 입니다.','F',SYSDATE,SYSDATE,'P0009','testing',120000);


INSERT INTO PRODBOARD VALUES
((SELECT NVL(MAX(BOARD_ID),0)+1 FROM PRODBOARD),'캐시미어 니트 경량 패딩',
'5번쯤 착용했어요 하자없고 깨끗합니다~','F',SYSDATE,SYSDATE,'P0017','test99',100000);

INSERT INTO PRODBOARD VALUES
((SELECT NVL(MAX(BOARD_ID),0)+1 FROM PRODBOARD),'타이니러브 모빌(월평동, 만년동)',
'택배거래가 어려워 직거래만 합니다. 대전 월평동 혹은 만년동으로 직접가지러 와주세요.','F',SYSDATE,SYSDATE,'P0025','test99',35000);

INSERT INTO PRODBOARD VALUES
((SELECT NVL(MAX(BOARD_ID),0)+1 FROM PRODBOARD),'캐시미어 니트 경량 패딩',
'5번쯤 착용했어요 하자없고 깨끗합니다~','T',SYSDATE,SYSDATE,'P0017','test99',100000);

INSERT INTO PRODBOARD VALUES
((SELECT NVL(MAX(BOARD_ID),0)+1 FROM PRODBOARD),'가이거 오토메틱시계팝니다',
'상태좋아요~','T',SYSDATE,SYSDATE,'P0009','test99',70000);

COMMIT;

:: VIEW ::
--CREATE OR REPLACE VIEW MYPAGE_SELECT 
--AS
--SELECT 
--FROM PRODBOARD WHERE MEM_ID = 'red0101';


:: 컬럼수정 ::
ALTER TABLE CATEGORY MODIFY(CATE_NAME VARCHAR2(4000));

ALTER TABLE PRODBOARD MODIFY(BOARD_TITTLE VARCHAR2(4000));
ALTER TABLE PRODBOARD MODIFY(BOARD_CONTENTS VARCHAR2(4000));

UPDATE MEMBER
    SET MEM_ID = 'red0101'
where MEM_ID = '안녕';

commit;

:: 행 삭제 ::
DELETE FROM CATEGORY
WHERE CATE_NAME='예시';


:: 카테고리 테이블 ::
INSERT INTO CATEGORY VALUES('P0001','컴퓨터');
INSERT INTO CATEGORY VALUES('P0002','출산육아'); 
INSERT INTO CATEGORY VALUES('P0003','자동차');
INSERT INTO CATEGORY VALUES('P0004','디지털/가전');
INSERT INTO CATEGORY VALUES('P0005','산업용품');
INSERT INTO CATEGORY VALUES('P0006','상품권/티켓/쿠폰');
INSERT INTO CATEGORY VALUES('P0007','캠핑');
INSERT INTO CATEGORY VALUES('P0008','미용');
INSERT INTO CATEGORY VALUES('P0009','귀금속/주얼리/악세서리');
INSERT INTO CATEGORY VALUES('P0010','자전거');
INSERT INTO CATEGORY VALUES('P0011','게임용품');
INSERT INTO CATEGORY VALUES('P0012','오토바이');
INSERT INTO CATEGORY VALUES('P0013','미술/음악');
INSERT INTO CATEGORY VALUES('P0014','예술/취미/수집');
INSERT INTO CATEGORY VALUES('P0015','골프');
INSERT INTO CATEGORY VALUES('P0016','명품');
INSERT INTO CATEGORY VALUES('P0017','여성의류/잡화');
INSERT INTO CATEGORY VALUES('P0018','남성의류/잡화');
INSERT INTO CATEGORY VALUES('P0019','기타의류잡화');
INSERT INTO CATEGORY VALUES('P0020','여행/여가활동');
INSERT INTO CATEGORY VALUES('P0021','카메라');
INSERT INTO CATEGORY VALUES('P0022','도서관련');
INSERT INTO CATEGORY VALUES('P0023','스타굿즈');
INSERT INTO CATEGORY VALUES('P0024','스포츠/레저');
INSERT INTO CATEGORY VALUES('P0025','홈/샐황용품');
INSERT INTO CATEGORY VALUES('P0026','반려동물용품');
INSERT INTO CATEGORY VALUES('P0027','키덜트');
INSERT INTO CATEGORY VALUES('P0028','가구');


INSERT INTO RATING VALUES('red0101','testing','4','최고예요~',SYSDATE);
INSERT INTO RATING VALUES('red0101','test99','5','거래 깔끔하게 잘하시네요',SYSDATE);
INSERT INTO RATING VALUES('testing','test99','5','최고의 거래~!',SYSDATE);
INSERT INTO RATING VALUES('샘플아이디2','test99','1','음 저는별로....',SYSDATE);
INSERT INTO RATING VALUES('샘플아이디1','test99','3','연락좀 확인해주세요~!',SYSDATE);
INSERT INTO RATING VALUES('test99','testing','4','거래 감사합니다',SYSDATE);
INSERT INTO RATING VALUES('샘플아이디2','testing','5','물건잘받았습니다.',SYSDATE);

COMMIT;



SELECT SUM(BOARD_PRICE)
 FROM PRODBOARD
WHERE STATUS = 'T' AND MEM_ID = 'test99';


//총수익금액, 회원등급
SELECT SUM(A.BOARD_PRICE) AS SUMCION,
						B.MEM_GRADE
					 	FROM PRODBOARD A, MEMBER B
					  WHERE A.MEM_ID = B.MEM_ID
                      AND A.STATUS = 'T' AND A.MEM_ID = 'test99'
                      GROUP BY B.MEM_GRADE
					

