ALTER TABLE STAYMYLIST ADD CONSTRAINT STAYMYLIST_email foreign KEY(MEM_EMAIL) references MEMBER (MEM_EMAIL);

ALTER TABLE STAYMYLIST ADD CONSTRAINT STAYMYLIST_STAY_NO foreign KEY(STAY_NO) references STAY (STAY_NO);